# will try ~/git/runelite by default
# runelite_dir = "/path/to/runelite/repo"

# will try ~/.runelite/action-logger by default
# action_logger_log_dir = "/path/to/actionlogger/log/dir"

[tail]
show_inventory_changes = false
show_dialogue_events = false
show_animation_changes = false

filtered_varbits = [
    8354, # varbit CLOCK
    9657, # varbit SETTINGS_SELECTED_SETTING
    11534, # varbit OSM_HOTKEY_0
    11535, # varbit OSM_HOTKEY_1
    11536, # varbit OSM_HOTKEY_2
    11537, # varbit OSM_HOTKEY_3
    11538, # varbit OSM_HOTKEY_4
    11540, # varbit OSM_HOTKEY_LOADOUT1_0
    11541, # varbit OSM_HOTKEY_LOADOUT1_1
    11542, # varbit OSM_HOTKEY_LOADOUT1_2
    11543, # varbit OSM_HOTKEY_LOADOUT1_3
    11544, # varbit OSM_HOTKEY_LOADOUT1_4
    11545, # varbit OSM_HOTKEY_LOADOUT2_0
    11546, # varbit OSM_HOTKEY_LOADOUT2_1
    11547, # varbit OSM_HOTKEY_LOADOUT2_2
    11548, # varbit OSM_HOTKEY_LOADOUT2_3
    11549, # varbit OSM_HOTKEY_LOADOUT2_4
    11550, # varbit OSM_HOTKEY_LOADOUT3_0
    11551, # varbit OSM_HOTKEY_LOADOUT3_1
    11552, # varbit OSM_HOTKEY_LOADOUT3_2
    11553, # varbit OSM_HOTKEY_LOADOUT3_3
    11554, # varbit OSM_HOTKEY_LOADOUT3_4
    357, # varbit COMBAT_WEAPON_CATEGORY

    12427, # varbit OPTION_SOUNDS_SAVED


    4605, # varbit MULTIWAY_INDICATOR

    10670, # varbit CHATMODAL_UNCLAMP


    4137, # varbit MUSIC_ENABLELOOP
    4606, # varbit FOV_CLAMP
    6719, # varbit MINIMAP_STATE
    12139, # varbit GRAVESTONE_TLI_HIDE

    12164, # varbit CLAN_GUEST_AFFINITYSTATUS
    933, # varbit CLAN_AFFINITYSTATUS
    13989, # varbit PVPA_AFFINITYSTATUS



    17775, # varbit OPTION_HIDE_ROOFTOPS_OVERRIDE

    6099, # varbit HPBAR_HUD_HP

    5934, # varbit FOSSIL_MINE_TEMP_PTS - keeps randomly increasing 1 at a time. not sure what this does. something with volcanic mine?

    6100, # varbit HPBAR_HUD_BASEHP
    6100, # varbit HPBAR_HUD_BASEHP
    12401, # varbit HPBAR_HUD_BOSS

    8061, # varbit PURGEIGNORED_STATUS


    13027, # varbit COMBATLEVEL_TRANSMIT

]

filtered_varps = [
    1683, # varp HPBAR_HUD_NPC
    4066, # varp MUSICMULTI_24
    662, # varp MUSICMULTI_13
    4720, # varp AUTOCAST_SPELL_OBJ
    4725, # varp GE_LAST_OFFER_ITEM
    4731, # varp LOGIN_TIME

    4411, # varp MUSICMULTI_25


    43, # varp COM_MODE
    46, # varp COM_STANCE
    261, # varp IF1
    262, # varp IF2
    263, # varp IF3
    4512, # varp TRACKING_COINS_GAINED
    4513, # varp TRACKING_COINS_LOST
    4514, # varp TRACKING_DAMAGE_DEALT_TO_NPCS
    4516, # varp TRACKING_DAMAGE_TAKEN_FROM_NPCS
    4518, # varp TRACKING_FOOD_EATEN
    4520, # varp TRACKING_HIGHEST_VALUE_ITEM_WORN
    4521, # varp TRACKING_MONSTERS_KILLED
    4525, # varp TRACKING_LOGS_CHOPPED
    4526, # varp TRACKING_ORE_MINED
    169, # varp OPTION_SOUNDS
    872, # varp OPTION_AREASOUNDS
    4623, # varp COLLECTION_OVERVIEW_LAST_ITEM0
    4625, # varp COLLECTION_OVERVIEW_LAST_ITEM1
    4627, # varp COLLECTION_OVERVIEW_LAST_ITEM2
    4629, # varp COLLECTION_OVERVIEW_LAST_ITEM3
    4631, # varp COLLECTION_OVERVIEW_LAST_ITEM4
    4633, # varp COLLECTION_OVERVIEW_LAST_ITEM5
    4635, # varp COLLECTION_OVERVIEW_LAST_ITEM6
    4637, # varp COLLECTION_OVERVIEW_LAST_ITEM7
    4639, # varp COLLECTION_OVERVIEW_LAST_ITEM8
    4641, # varp COLLECTION_OVERVIEW_LAST_ITEM9
    4643, # varp COLLECTION_OVERVIEW_LAST_ITEM10
    4645, # varp COLLECTION_OVERVIEW_LAST_ITEM11

    4278, # varp POTIONSTORE_FAVOURITE_1
    4279, # varp POTIONSTORE_FAVOURITE_2
    4280, # varp POTIONSTORE_FAVOURITE_3
    4281, # varp POTIONSTORE_FAVOURITE_4
    4282, # varp POTIONSTORE_FAVOURITE_5
    4283, # varp POTIONSTORE_FAVOURITE_6
    4284, # varp POTIONSTORE_FAVOURITE_7
    4285, # varp POTIONSTORE_FAVOURITE_8
    4385, # varp BANK_VIEWCONTAINER_OBJ
    4458, # varp PREPOT_DEVICE_LOADOUT_0_SLOT_0_POTION
    4459, # varp PREPOT_DEVICE_LOADOUT_0_SLOT_1_POTION
    4460, # varp PREPOT_DEVICE_LOADOUT_0_SLOT_2_POTION
    4461, # varp PREPOT_DEVICE_LOADOUT_0_SLOT_3_POTION
    4462, # varp PREPOT_DEVICE_LOADOUT_0_SLOT_4_POTION
    4463, # varp PREPOT_DEVICE_LOADOUT_1_SLOT_0_POTION
    4464, # varp PREPOT_DEVICE_LOADOUT_1_SLOT_1_POTION
    4465, # varp PREPOT_DEVICE_LOADOUT_1_SLOT_2_POTION
    4466, # varp PREPOT_DEVICE_LOADOUT_1_SLOT_3_POTION
    4467, # varp PREPOT_DEVICE_LOADOUT_1_SLOT_4_POTION
    4468, # varp PREPOT_DEVICE_LOADOUT_2_SLOT_0_POTION
    4469, # varp PREPOT_DEVICE_LOADOUT_2_SLOT_1_POTION
    4470, # varp PREPOT_DEVICE_LOADOUT_2_SLOT_2_POTION
    4471, # varp PREPOT_DEVICE_LOADOUT_2_SLOT_3_POTION
    4472, # varp PREPOT_DEVICE_LOADOUT_2_SLOT_4_POTION
    4473, # varp PREPOT_DEVICE_LOADOUT_3_SLOT_0_POTION
    4474, # varp PREPOT_DEVICE_LOADOUT_3_SLOT_1_POTION
    4475, # varp PREPOT_DEVICE_LOADOUT_3_SLOT_2_POTION
    4476, # varp PREPOT_DEVICE_LOADOUT_3_SLOT_3_POTION
    4477, # varp PREPOT_DEVICE_LOADOUT_3_SLOT_4_POTION


    18, # varp MUSICPLAY
    20, # varp MUSICMULTI_1
    21, # varp MUSICMULTI_2
    22, # varp MUSICMULTI_3
    23, # varp MUSICMULTI_4
    24, # varp MUSICMULTI_5
    25, # varp MUSICMULTI_6
    298, # varp MUSICMULTI_7
    311, # varp MUSICMULTI_8
    346, # varp MUSICMULTI_9
    464, # varp MUSICMULTI_11
    721, # varp MUSICMULTI_14
    2237, # varp MUSICMULTI_20
    2950, # varp MUSICMULTI_21





    173, # varp OPTION_RUN

    168, # varp OPTION_MUSIC


]
