# will try ~/git/runelite by default
# runelite_dir = "/path/to/runelite/repo"

# will try ~/.runelite/action-logger by default
# action_logger_log_dir = "/path/to/actionlogger/log/dir"

[tail]
show_inventory_changes = false
show_dialogue_events = false
show_animation_changes = false

filtered_varbits = [
    8354, # varbit CLOCK
    9657, # varbit SETTINGS_SELECTED_SETTING
    11534, # varbit OSM_HOTKEY_0
    11535, # varbit OSM_HOTKEY_1
    11536, # varbit OSM_HOTKEY_2
    11537, # varbit OSM_HOTKEY_3
    11538, # varbit OSM_HOTKEY_4
    11540, # varbit OSM_HOTKEY_LOADOUT1_0
    11541, # varbit OSM_HOTKEY_LOADOUT1_1
    11542, # varbit OSM_HOTKEY_LOADOUT1_2
    11543, # varbit OSM_HOTKEY_LOADOUT1_3
    11544, # varbit OSM_HOTKEY_LOADOUT1_4
    11545, # varbit OSM_HOTKEY_LOADOUT2_0
    11546, # varbit OSM_HOTKEY_LOADOUT2_1
    11547, # varbit OSM_HOTKEY_LOADOUT2_2
    11548, # varbit OSM_HOTKEY_LOADOUT2_3
    11549, # varbit OSM_HOTKEY_LOADOUT2_4
    11550, # varbit OSM_HOTKEY_LOADOUT3_0
    11551, # varbit OSM_HOTKEY_LOADOUT3_1
    11552, # varbit OSM_HOTKEY_LOADOUT3_2
    11553, # varbit OSM_HOTKEY_LOADOUT3_3
    11554, # varbit OSM_HOTKEY_LOADOUT3_4
    357, # varbit COMBAT_WEAPON_CATEGORY

    12427, # varbit OPTION_SOUNDS_SAVED


    4605, # varbit MULTIWAY_INDICATOR

    10670, # varbit CHATMODAL_UNCLAMP


    4137, # varbit MUSIC_ENABLELOOP
    4606, # varbit FOV_CLAMP
    6719, # varbit MINIMAP_STATE
    12139, # varbit GRAVESTONE_TLI_HIDE

    12164, # varbit CLAN_GUEST_AFFINITYSTATUS
    933, # varbit CLAN_AFFINITYSTATUS
    13989, # varbit PVPA_AFFINITYSTATUS



    17775, # varbit OPTION_HIDE_ROOFTOPS_OVERRIDE

    6099, # varbit HPBAR_HUD_HP

    5934, # varbit FOSSIL_MINE_TEMP_PTS - keeps randomly increasing 1 at a time. not sure what this does. something with volcanic mine?

    6100, # varbit HPBAR_HUD_BASEHP
    6100, # varbit HPBAR_HUD_BASEHP
    12401, # varbit HPBAR_HUD_BOSS

    8061, # varbit PURGEIGNORED_STATUS


    13027, # varbit COMBATLEVEL_TRANSMIT

    13071, # varbit SIDE_CHANNELS_TAB_SELECTED

    12169, # varbit CLAN_TRANSMIT_GUEST_TIMEOUT
    13128, # varbit CLAN_GUEST_AFFINITY_JOINED
    12168, # varbit CLAN_TRANSMIT_GUEST_HOMEWORLD
    12169, # varbit CLAN_TRANSMIT_GUEST_TIMEOUT

    13093, # varbit XPTRACKER_STRENGTH_MULTIPLIER
    13095, # varbit XPTRACKER_HITPOINTS_MULTIPLIER

    10542, # varbit WORN_ITEMS_GRACEFUL_SET
    10538, # varbit WORN_ITEMS_GRACEFUL_LEGS
    10542, # varbit WORN_ITEMS_GRACEFUL_SET
    10539, # varbit WORN_ITEMS_GRACEFUL_BOOTS
    10542, # varbit WORN_ITEMS_GRACEFUL_SET
    10536, # varbit WORN_ITEMS_GRACEFUL_HOOD
    10542, # varbit WORN_ITEMS_GRACEFUL_SET
    10541, # varbit WORN_ITEMS_GRACEFUL_CAPE
    10542, # varbit WORN_ITEMS_GRACEFUL_SET
    10540, # varbit WORN_ITEMS_GRACEFUL_GLOVES
    10542, # varbit WORN_ITEMS_GRACEFUL_SET
    10541, # varbit WORN_ITEMS_GRACEFUL_CAPE
    10539, # varbit WORN_ITEMS_GRACEFUL_BOOTS
    10540, # varbit WORN_ITEMS_GRACEFUL_GLOVES
    10538, # varbit WORN_ITEMS_GRACEFUL_LEGS
    10536, # varbit WORN_ITEMS_GRACEFUL_HOOD
    10537, # varbit WORN_ITEMS_GRACEFUL_TORSO
    10535, # varbit WORN_ITEMS_SET_TEXT

    11563, # varbit BANK_ADD_LASTSLOT
    276, # varbit AUTOCAST_SPELL

    19104, # varbit SAILING_PLAYER_IS_ON_PLAYER_BOAT
    19105, # varbit SAILING_BOAT_FACILITY_LOCKEDIN
    19122, # varbit SAILING_BOARDED_BOAT_WORLD
    19129, # varbit SAILING_BOAT_SPAWNED_ANGLE
    19136, # varbit SAILING_BOARDED_BOAT
    19137, # varbit SAILING_BOARDED_BOAT_TYPE
    19141, # varbit SAILING_BOAT_SPAWNED_FINEX
    19142, # varbit SAILING_BOAT_SPAWNED_FINEZ
    19145, # varbit SAILING_BOARDED_BOAT_LAST_DOCK
    19146, # varbit SAILING_BOARDED_BOAT_LAST_STANDARD_DOCK
    19151, # varbit SAILING_SIDEPANEL_VISIBLE
    19154, # varbit SAILING_SIDEPANEL_FACILITY_SAIL
    19155, # varbit SAILING_SIDEPANEL_FACILITY_HELM
    19158, # varbit SAILING_SIDEPANEL_FACILITY_HOTSPOT2
    19160, # varbit SAILING_SIDEPANEL_FACILITY_HOTSPOT4
    19162, # varbit SAILING_SIDEPANEL_FACILITY_HOTSPOT6
    19167, # varbit SAILING_SIDEPANEL_FACILITY_KEEL
    19168, # varbit SAILING_SIDEPANEL_FACILITY_HULL
    19172, # varbit SAILING_SIDEPANEL_FACILITY_TRIM
    19174, # varbit SAILING_SIDEPANEL_SAIL_BUTTON_TOGGLED
    19175, # varbit SAILING_SIDEPANEL_BOAT_MOVE_MODE
    19176, # varbit SAILING_SIDEPANEL_HELM_STATUS
    19177, # varbit SAILING_SIDEPANEL_BOAT_HP_MAX
    19205, # varbit SAILING_SIDEPANEL_PLAYER_AT_HELM
    19235, # varbit SAILING_SIDEPANEL_PLAYERS_ON_BOARD_TOTAL
    19236, # varbit SAILING_SIDEPANEL_AMMO_NEEDS_UPDATE
    19237, # varbit SAILING_SIDEPANEL_BOAT_STATS_NEEDS_UPDATE
    19243, # varbit SAILING_SIDEPANEL_CREW_SLOT_1
    19248, # varbit SAILING_SIDEPANEL_BOAT_STORMRESISTANCE
    19249, # varbit SAILING_SIDEPANEL_BOAT_RAPIDRESISTANCE
    19250, # varbit SAILING_SIDEPANEL_BOAT_BASESPEED
    19251, # varbit SAILING_SIDEPANEL_BOAT_SPEEDCAP
    19256, # varbit SAILING_SIDEPANEL_BOAT_SPEEDBOOST_DURATION
    19257, # varbit SAILING_SIDEPANEL_BOAT_ACCELERATION
    19298, # varbit SAILING_BOAT_2_PORT
    19493, # varbit SAILING_CREW_GENERIC_1_VISIBILITY
    19503, # varbit SAILING_CREW_ON_DOCK

    4398, # varbit GE_NEWOFFER_PRICE

    4773, # varbit FARMING_TRANSMIT_C
    4957, # varbit FARMING_TRANSMIT_C1
    4958, # varbit FARMING_TRANSMIT_C2
    4771, # varbit FARMING_TRANSMIT_A
    4953, # varbit FARMING_TRANSMIT_A1
    4954, # varbit FARMING_TRANSMIT_A2
    4773, # varbit FARMING_TRANSMIT_C
    4957, # varbit FARMING_TRANSMIT_C1
    4958, # varbit FARMING_TRANSMIT_C2
    4771, # varbit FARMING_TRANSMIT_A
    4953, # varbit FARMING_TRANSMIT_A1
    4954, # varbit FARMING_TRANSMIT_A2

    12391, # varbit DATE_MILLISECONDS_PAST_MINUTE
    12392, # varbit DATE_SECONDS_PAST_MINUTE

    12393, # varbit BUSY

    3958, # varbit BANK_WITHDRAWNOTES

    6348, # varbit SHOP_QUANTITY
]

filtered_varps = [
    1683, # varp HPBAR_HUD_NPC
    4066, # varp MUSICMULTI_24
    662, # varp MUSICMULTI_13
    4720, # varp AUTOCAST_SPELL_OBJ
    4725, # varp GE_LAST_OFFER_ITEM
    4731, # varp LOGIN_TIME

    4411, # varp MUSICMULTI_25


    43, # varp COM_MODE
    46, # varp COM_STANCE
    261, # varp IF1
    262, # varp IF2
    263, # varp IF3
    4512, # varp TRACKING_COINS_GAINED
    4513, # varp TRACKING_COINS_LOST
    4514, # varp TRACKING_DAMAGE_DEALT_TO_NPCS
    4516, # varp TRACKING_DAMAGE_TAKEN_FROM_NPCS
    4518, # varp TRACKING_FOOD_EATEN
    4520, # varp TRACKING_HIGHEST_VALUE_ITEM_WORN
    4521, # varp TRACKING_MONSTERS_KILLED
    4525, # varp TRACKING_LOGS_CHOPPED
    4526, # varp TRACKING_ORE_MINED
    169, # varp OPTION_SOUNDS
    872, # varp OPTION_AREASOUNDS
    4623, # varp COLLECTION_OVERVIEW_LAST_ITEM0
    4625, # varp COLLECTION_OVERVIEW_LAST_ITEM1
    4627, # varp COLLECTION_OVERVIEW_LAST_ITEM2
    4629, # varp COLLECTION_OVERVIEW_LAST_ITEM3
    4631, # varp COLLECTION_OVERVIEW_LAST_ITEM4
    4633, # varp COLLECTION_OVERVIEW_LAST_ITEM5
    4635, # varp COLLECTION_OVERVIEW_LAST_ITEM6
    4637, # varp COLLECTION_OVERVIEW_LAST_ITEM7
    4639, # varp COLLECTION_OVERVIEW_LAST_ITEM8
    4641, # varp COLLECTION_OVERVIEW_LAST_ITEM9
    4643, # varp COLLECTION_OVERVIEW_LAST_ITEM10
    4645, # varp COLLECTION_OVERVIEW_LAST_ITEM11

    4278, # varp POTIONSTORE_FAVOURITE_1
    4279, # varp POTIONSTORE_FAVOURITE_2
    4280, # varp POTIONSTORE_FAVOURITE_3
    4281, # varp POTIONSTORE_FAVOURITE_4
    4282, # varp POTIONSTORE_FAVOURITE_5
    4283, # varp POTIONSTORE_FAVOURITE_6
    4284, # varp POTIONSTORE_FAVOURITE_7
    4285, # varp POTIONSTORE_FAVOURITE_8
    4385, # varp BANK_VIEWCONTAINER_OBJ
    4458, # varp PREPOT_DEVICE_LOADOUT_0_SLOT_0_POTION
    4459, # varp PREPOT_DEVICE_LOADOUT_0_SLOT_1_POTION
    4460, # varp PREPOT_DEVICE_LOADOUT_0_SLOT_2_POTION
    4461, # varp PREPOT_DEVICE_LOADOUT_0_SLOT_3_POTION
    4462, # varp PREPOT_DEVICE_LOADOUT_0_SLOT_4_POTION
    4463, # varp PREPOT_DEVICE_LOADOUT_1_SLOT_0_POTION
    4464, # varp PREPOT_DEVICE_LOADOUT_1_SLOT_1_POTION
    4465, # varp PREPOT_DEVICE_LOADOUT_1_SLOT_2_POTION
    4466, # varp PREPOT_DEVICE_LOADOUT_1_SLOT_3_POTION
    4467, # varp PREPOT_DEVICE_LOADOUT_1_SLOT_4_POTION
    4468, # varp PREPOT_DEVICE_LOADOUT_2_SLOT_0_POTION
    4469, # varp PREPOT_DEVICE_LOADOUT_2_SLOT_1_POTION
    4470, # varp PREPOT_DEVICE_LOADOUT_2_SLOT_2_POTION
    4471, # varp PREPOT_DEVICE_LOADOUT_2_SLOT_3_POTION
    4472, # varp PREPOT_DEVICE_LOADOUT_2_SLOT_4_POTION
    4473, # varp PREPOT_DEVICE_LOADOUT_3_SLOT_0_POTION
    4474, # varp PREPOT_DEVICE_LOADOUT_3_SLOT_1_POTION
    4475, # varp PREPOT_DEVICE_LOADOUT_3_SLOT_2_POTION
    4476, # varp PREPOT_DEVICE_LOADOUT_3_SLOT_3_POTION
    4477, # varp PREPOT_DEVICE_LOADOUT_3_SLOT_4_POTION


    18, # varp MUSICPLAY
    20, # varp MUSICMULTI_1
    21, # varp MUSICMULTI_2
    22, # varp MUSICMULTI_3
    23, # varp MUSICMULTI_4
    24, # varp MUSICMULTI_5
    25, # varp MUSICMULTI_6
    298, # varp MUSICMULTI_7
    311, # varp MUSICMULTI_8
    346, # varp MUSICMULTI_9
    414, # varp MUSICMULTI_10
    464, # varp MUSICMULTI_11
    721, # varp MUSICMULTI_14
    1009, # varp MUSICMULTI_16
    2237, # varp MUSICMULTI_20
    2950, # varp MUSICMULTI_21
    3418, # varp MUSICMULTI_22
    4944, # varp MUSICMULTI_26




    173, # varp OPTION_RUN

    168, # varp OPTION_MUSIC


    5117, # varp SAILING_SIDEPANEL_BOAT_TYPE
    5147, # varp SAILING_SIDEPANEL_BOAT_DEFENCE
    5148, # varp SAILING_SIDEPANEL_BOAT_ARMOUR
    5159, # varp SAILING_SIDEPANEL_BOATSTAT_TOTAL_STABDEF
    5160, # varp SAILING_SIDEPANEL_BOATSTAT_TOTAL_SLASHDEF
    5161, # varp SAILING_SIDEPANEL_BOATSTAT_TOTAL_CRUSHDEF
    5162, # varp SAILING_SIDEPANEL_BOATSTAT_TOTAL_MAGICDEF
    5163, # varp SAILING_SIDEPANEL_BOATSTAT_TOTAL_HEAVYRANGEDDEF
    5164, # varp SAILING_SIDEPANEL_BOATSTAT_TOTAL_STANDARDRANGEDDEF
    5165, # varp SAILING_SIDEPANEL_BOATSTAT_TOTAL_LIGHTRANGEDDEF
    5204, # varp SAILING_BOAT_CARGOHOLD_INV
    5205, # varp SAILING_BOAT_CARGOHOLD_SIDE_WHITELIST

    
    3679, # varp LATEST_QUEST_JOURNAL
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    4398, # varp QJ_LINES
    3078, # varp DATE_MINUTES
    3079, # varp MAP_CLOCK

    888, # varp SLUG2_REGIONUID
    3883, # varp MUSIC_CURRENT_TRACK
]

